### ISSUE TITLE
Position context pad always on canvas

### ISSUE THREAD

**Issue by nikku** [camunda/improved-canvas#19]
### Describe the issue

As a user I want to have my context pad always accessible. At this time, however, it is easy for the menu to move out of the canvas:

![capture fxSW5l_optimized](https://github.com/camunda/improved-canvas/assets/58601/b0d28130-1286-4be3-b0d5-91c8c049a3b2)

### Describe the solution you like

Position the menu relative to the element, but in a smart manner. When there is no place left (or top), position it to the bottom.

If popup menus open, ensure these are positioned in a proper way (away from the element, not hidden if possible, too).

### Context

Came up in a user test.

**Comment by philippfromme** [comment]
Closed by https://github.com/camunda/improved-canvas/pull/61.
