### ISSUE TITLE
Support "call to action" entry in context pad

### ISSUE THREAD

**Issue by smbea** [camunda/improved-canvas#23]
### What should we do?
Support a highlighted context pad entry (which will be used for resource linking in bpmn):

<img width="250" src="https://github.com/camunda/improved-canvas/assets/25825387/67055010-d922-4251-ac79-3a55946929b5"/>
<img width="250" src="https://github.com/camunda/improved-canvas/assets/25825387/838c2069-97bf-43be-b5f4-ba080bbcddc0"/>
<img width="250"src="https://github.com/camunda/improved-canvas/assets/25825387/3c34beec-bd09-456c-87ea-3da4f97b7109"/>

###  Why should we do it?
As part of the intuitive modeling initiative, see https://github.com/camunda/product-hub/issues/1917

**Comment by nikku** [comment]
Cf. https://github.com/camunda/product-hub/issues/1917#issuecomment-1896594699. 

Let's ensure we plug form linking validation in first.

**Comment by smbea** [comment]
I opened a PR for this: https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/151
