### ISSUE TITLE
Popup Menu Position Off

### ISSUE THREAD

**Issue by philippfromme** [camunda/improved-canvas#37]
The position of the popup menu isn't always correct.

In bpmn-js it's correct:

![image](https://github.com/camunda/improved-canvas/assets/7633572/12dc492e-7c38-43fd-8c22-5ecb9d2b8e1c)

In dmn-js it's off:

![image](https://github.com/camunda/improved-canvas/assets/7633572/efdc1c86-caeb-426d-9954-fbcd89e02c84)

This seems to be an issue in the core.

---

Related to https://github.com/camunda/web-modeler/pull/7847
Depends on https://github.com/bpmn-io/diagram-js/pull/878

**Comment by nikku** [comment]
Fixed via https://github.com/bpmn-io/diagram-js/blob/develop/CHANGELOG.md#1432.

**Comment by nikku** [comment]
Already incorporated in this library :heavy_check_mark:
