### ISSUE TITLE
Change order of context pad entries to account for left to right modeling

### ISSUE THREAD

**Issue by philippfromme** [camunda/improved-canvas#54]
The current order of the context pad entries is opposite to the modeling direction. Modeling is left to right, while the most commonly used context pad icons are on the left. We should change the order to account for left to right modeling and to minimize cursor movement.

![image](https://github.com/camunda/improved-canvas/assets/7633572/a02748b3-4a1f-4023-99d2-72ae5c70848f)

**Comment by lmbateman** [comment]
Just ran an analysis for quick-append elements, combining the duplicates:
<img width="508" alt="image" src="https://github.com/camunda/improved-canvas/assets/148087642/0cea7bc2-9d5f-4c15-8252-85b9d2257c21">

Numbers are percentages of total context pad clicks.
